### ISSUE TITLE
Outline window forcibly jumps up while scrolling

### ISSUE THREAD

**Issue by z3z1ma** [hedyhli/symbols-outline.nvim#7]
The window keeps forcibly jumping to seemingly arbitrary symbols so often that I cannot scroll the the bottom of the window
Even using `G` to go to the bottom, it jumps back up to an arbitrary node.

The only thing I see before it happens are some nodes have highlights like below and the window jumps up. Is there any codepath that would cause forced scrolling to nodes? While just pressing `j`/`k` in the outline window?

<img width="479" alt="image" src="https://github.com/hedyhli/symbols-outline.nvim/assets/41213451/c9624f3b-c728-4070-9566-ef31cb262d4b">

**Comment by z3z1ma** [comment]
Tried it in python file too

Same thing. I was at the very bottom of the outline window after pressing `G` and with no other keypress it just jumps back up by itself to these nodes. Mind that my cursor is not at these nodes. 

<img width="460" alt="image" src="https://github.com/hedyhli/symbols-outline.nvim/assets/41213451/6f47fb4b-9786-4826-8dc1-0e846de464c8">

**Comment by gennaro-tedesco** [comment]
I confirm seeing this too (in lua, go, python and rust at least).

**Comment by hedyhli** [comment]
This is definitely an annoyance, thanks for reporting.

I believe it is now fixed, but do let me know if it is otherwise.

It will not update the outline items nor cursor position when cursor is in outline window, however you can use `<C-g>` when in the outline window to do so manually (or [`:SymbolsOutlineFollow[!]`](https://github.com/hedyhli/symbols-outline.nvim#commands) from code window).

**Comment by hedyhli** [comment]
> Mind that my cursor is not at these nodes.

This is currently a known issue that is observed only seldomly for me, it will be tracked here: #1
